package wiki

// docs holds one FixDoc per step ID, per language. Every ID that
// engine.orderedSteps() applies must have an entry in BOTH languages
// (see wiki_test.go: TestEveryStepHasDoc). Text is novice-friendly and
// short — each field renders in a narrow terminal pane.
var docs = map[Lang]map[string]FixDoc{
	RU: {
		"PRE": {
			Title:       "Подготовка и проверки",
			What:        "Обновляет список пакетов apt, создаёт администраторского пользователя с sudo и SSH-ключом, проверяет версию ОС и режим защиты.",
			Why:         "Гарантирует, что есть рабочий вход без root и что установка пакетов не упадёт ещё до начала настройки.",
			RiskWithout: "Первая же установка пакета может провалиться, а блокировка SSH без запасного пользователя приведёт к полной потере доступа к серверу.",
			OnBox:       "Создаёт пользователя (adduser) с группами sudo и sshusers, кладёт ключ в /home/<user>/.ssh/authorized_keys, пишет NOPASSWD-правило /etc/sudoers.d/90-<user>; в режиме soft задаёт консольный пароль (chpasswd).",
			Revert:      "deluser --remove-home <user> + delgroup sshusers; удалить /etc/sudoers.d/90-<user>; автоотката в программе нет.",
		},
		"A1": {
			Title:       "Межсетевой экран",
			What:        "Закрывает все входящие порты кроме SSH через iptables (IPv4 и IPv6) и сохраняет правила до перезагрузки. Перед изменением ставит таймер-страховку, который откатит правила, если связь пропадёт.",
			Why:         "Сервер перестаёт быть виден из интернета по любым службам, кроме нужных, а страховка не даёт случайно заблокировать самого себя.",
			RiskWithout: "Любая служба, случайно слушающая порт, открыта всему интернету для атак и сканирования.",
			OnBox:       "Правила iptables/ip6tables (политика INPUT DROP), сохранённые в /etc/iptables/rules.v4 и rules.v6; пакет iptables-persistent; бэкап в /root/iptables-backup.v4/.v6 и скрипт-страховка /usr/local/sbin/fw-rollback.sh.",
			Revert:      "iptables -P INPUT ACCEPT; iptables -F (и ip6tables) либо iptables-restore < /root/iptables-backup.v4; затем netfilter-persistent save; при желании apt purge iptables-persistent; автоотката нет.",
		},
		"A8": {
			Title:       "Полное обновление и перезагрузка",
			What:        "Устанавливает все доступные обновления системы и перезагружает сервер, подтверждая успешную загрузку по смене boot_id.",
			Why:         "Закрывает известные уязвимости в ядре и пакетах и переводит сервер на свежие версии до тонкой настройки.",
			RiskWithout: "Система остаётся с устаревшим ядром и пакетами, содержащими публично известные дыры в безопасности.",
			OnBox:       "Выполняет apt-get full-upgrade (обновляет пакеты и ядро) и перезагружает сервер; постоянных конфигурационных файлов не пишет.",
			Revert:      "Обновления пакетов не откатываются штатно; при необходимости откатить ядро выбрать прежнюю версию в GRUB и зафиксировать пакет (apt-mark hold); автоотката нет.",
		},
		"A2": {
			Title:       "Усиление SSH",
			What:        "Отключает вход по паролю, разрешает только современные стойкие алгоритмы шифрования и пускает по SSH только участников группы sshusers.",
			Why:         "Делает невозможным подбор пароля по SSH и оставляет лишь надёжную криптографию и вход по ключу.",
			RiskWithout: "SSH остаётся открыт для перебора паролей и принимает слабые, устаревшие шифры.",
			OnBox:       "/etc/ssh/sshd_config.d/00-hardening.conf и 99-hardening.conf; на 26.04 постквантовый KEX mlkem768x25519-sha256; перезапуск ssh.",
			Revert:      "удалить drop-in'ы + systemctl restart ssh; при блокировке пароля root сначала разблокировать через консоль провайдера (passwd -u root); автоотката нет, но опасные изменения имеют ~300с страховку при срыве проверки входа.",
		},
		"A2.5": {
			Title:       "Нейтрализация cloud-init",
			What:        "Отключает службу cloud-init после завершения первичной настройки сервера.",
			Why:         "Не даёт провайдерскому cloud-init при каждой перезагрузке откатывать ваши настройки SSH и сети.",
			RiskWithout: "Любая будущая перезагрузка может незаметно вернуть часть настроек SSH и сети к небезопасным значениям по умолчанию.",
			OnBox:       "Создаёт файл-флаг /etc/cloud/cloud-init.disabled; сами пакеты cloud-init не удаляет.",
			Revert:      "rm /etc/cloud/cloud-init.disabled — cloud-init снова включится со следующей загрузки; автоотката нет.",
		},
		"A3": {
			Title:       "fail2ban",
			What:        "Ставит fail2ban, который следит за журналом и временно блокирует IP-адреса после нескольких неудачных попыток входа. Ваш админский IP вносится в белый список.",
			Why:         "Автоматически отсекает ботов, перебирающих доступ, и снижает шум в журналах.",
			RiskWithout: "Атакующие могут бесконечно долбить SSH неудачными попытками, не получая никаких ограничений.",
			OnBox:       "Пакеты fail2ban и python3-systemd; конфиг /etc/fail2ban/jail.local (jail sshd, белый список IP), при нестандартном порте — /etc/fail2ban/jail.d/sshd-port.local; служба fail2ban включена.",
			Revert:      "systemctl disable --now fail2ban; удалить /etc/fail2ban/jail.local (и jail.d/sshd-port.local); при желании apt purge fail2ban; автоотката нет.",
		},
		"A4": {
			Title:       "Сетевая оптимизация",
			What:        "Включает алгоритм управления перегрузкой BBR, увеличивает буферы сокетов и очереди сети через sysctl.",
			Why:         "Повышает пропускную способность и стабильность сетевых соединений, особенно на дальних маршрутах.",
			RiskWithout: "Сетевая производительность остаётся на консервативных значениях по умолчанию, не используя возможности канала.",
			OnBox:       "/etc/sysctl.d/99-bbr.conf (tcp_congestion_control=bbr, default_qdisc=fq) и 99-net-tune.conf (буферы); модуль tcp_bbr; переживает перезагрузку.",
			Revert:      "удалить оба файла + sysctl --system; модуль выгрузится после перезагрузки; автоотката в программе нет.",
		},
		"A5": {
			Title:       "Усиление ядра",
			What:        "Через sysctl ограничивает утечки информации о ядре, защищает символьные ссылки, блокирует подмену маршрутов и перенаправлений, отключает дампы памяти.",
			Why:         "Затрудняет локальную эскалацию привилегий и сетевой обман, оставляя меньше точек для атаки.",
			RiskWithout: "Ядро открывает атакующему адреса и подсказки для эксплойтов и принимает потенциально вредные сетевые пакеты.",
			OnBox:       "/etc/sysctl.d/99-zz-kernel-harden.conf (kptr_restrict, ptrace_scope, rp_filter=1, core_pattern=|/bin/false и др.); THP=madvise через /etc/default/grub (update-grub).",
			Revert:      "удалить 99-zz-kernel-harden.conf + sysctl --system; убрать transparent_hugepage=madvise из /etc/default/grub + update-grub; автоотката нет (rp_filter=1 имеет ~300с страховку при срыве проверки входа).",
		},
		"A6": {
			Title:       "Обслуживание системы",
			What:        "Ограничивает размер журналов systemd, настраивает неинтерактивный перезапуск служб, поднимает лимит открытых файлов и проверяет синхронизацию времени.",
			Why:         "Не даёт логам забить диск, обеспечивает корректные перезапуски после обновлений и точное системное время.",
			RiskWithout: "Журналы могут переполнить диск, обновления зависнуть на запросе, а службы упереться в низкий лимит файлов.",
			OnBox:       "drop-in'ы /etc/systemd/journald.conf.d/99-vps-cap.conf, /etc/needrestart/conf.d/50-autorestart.conf, /etc/systemd/system.conf.d/limits.conf; включает timedatectl set-ntp.",
			Revert:      "удалить три drop-in-файла; systemctl restart systemd-journald + systemctl daemon-reexec; автоотката нет.",
		},
		"A6.5": {
			Title:       "Защита DNS",
			What:        "Настраивает systemd-resolved на проверку DNSSEC и шифрование запросов через DNS-over-TLS в щадящем режиме.",
			Why:         "Затрудняет подмену и прослушивание DNS-запросов, не ломая совместимость с обычными сетями.",
			RiskWithout: "DNS-запросы идут открытым текстом без проверки подлинности и легко подменяются или прослушиваются.",
			OnBox:       "drop-in /etc/systemd/resolved.conf.d/99-morgward-dns.conf (DNS= с замеренными быстрейшими резолверами, DNSOverTLS=opportunistic, DNSSEC=allow-downgrade); перезапуск systemd-resolved.",
			Revert:      "удалить 99-morgward-dns.conf + systemctl restart systemd-resolved (вернётся DNS провайдера); автоотката нет (при поломке резолва шаг сам откатывается).",
		},
		"A6.7": {
			Title:       "Управление памятью",
			What:        "Включает сжатый своп в ОЗУ (ZRAM, zstd) и ставит earlyoom, который аккуратно завершает процессы до жёсткой нехватки памяти.",
			Why:         "Фактически расширяет доступную память и предотвращает зависание сервера при её исчерпании.",
			RiskWithout: "На малой памяти сервер может полностью зависнуть или жёстко убить важный процесс при нехватке ОЗУ.",
			OnBox:       "Пакеты systemd-zram-generator и earlyoom; /etc/systemd/zram-generator.conf (zram = ram/2, zstd) и /etc/sysctl.d/99-zram.conf (swappiness=180); отключает дисковый своп (swapoff + комментирует swap в /etc/fstab).",
			Revert:      "systemctl disable --now earlyoom; удалить zram-generator.conf и 99-zram.conf; вернуть строку swap в /etc/fstab и swapon -a; при желании apt purge systemd-zram-generator earlyoom; автоотката нет.",
		},
		"A7": {
			Title:       "Очистка системы",
			What:        "Удаляет ненужные на сервере пакеты (firmware-утилиты, отчётчики сбоев и прочий балласт), предварительно записав список в лог.",
			Why:         "Уменьшает поверхность атаки и расход ресурсов, убирая лишние службы.",
			RiskWithout: "Лишние пакеты держат ненужные службы и таймеры, расширяя поверхность атаки и потребление ресурсов.",
			OnBox:       "apt purge балласта (apport, whoopsie, sysstat, packagekit, на гостях fwupd, при безопасности multipath-tools) + apt autoremove --purge; список удалённого пишется в /root/vps-purged-packages.log.",
			Revert:      "Удаление пакетов необратимо; переустановить по списку из /root/vps-purged-packages.log командой apt install <пакеты>; автоотката нет.",
		},
		"A9": {
			Title:       "Автообновления безопасности",
			What:        "Включает unattended-upgrades для автоматической установки обновлений безопасности отдельным drop-in-файлом, без авто-перезагрузки.",
			Why:         "Критические патчи ставятся сами, без ручного вмешательства, при этом перезагрузки остаются под вашим контролем.",
			RiskWithout: "Исправления безопасности приходится ставить вручную, и сервер надолго остаётся уязвимым между обновлениями.",
			OnBox:       "Пакет unattended-upgrades; /etc/apt/apt.conf.d/20auto-upgrades (включает периодику) и 52-unattended-upgrades-local (Automatic-Reboot false, чистка ядер).",
			Revert:      "удалить оба файла из /etc/apt/apt.conf.d/ (либо systemctl disable --now apt-daily-upgrade.timer); при желании apt purge unattended-upgrades; автоотката нет.",
		},
		"A10": {
			Title:       "Обнаружение и мониторинг",
			What:        "Ставит auditd для журнала изменений важных файлов, уведомления об успешных входах по SSH и логирование отброшенных пакетов.",
			Why:         "Создаёт криминалистический след и оповещает о вторжении, тогда как fail2ban видит лишь неудачные попытки.",
			RiskWithout: "Успешный взлом, подмена конфигов и эскалация привилегий проходят незамеченными и без следов.",
			OnBox:       "Пакеты auditd/audispd-plugins + правила /etc/audit/rules.d/99-vps.rules; PAM-уведомление /usr/local/sbin/ssh-login-notify.sh (строка в /etc/pam.d/sshd); LOG-правила iptables; в strict — /etc/modprobe.d/99-vps-blacklist.conf и nodev/nosuid/noexec для /dev/shm в /etc/fstab.",
			Revert:      "systemctl disable --now auditd; удалить 99-vps.rules, строку из /etc/pam.d/sshd и ssh-login-notify.sh; убрать LOG-правила (iptables -D INPUT …); в strict удалить 99-vps-blacklist.conf и строку /dev/shm из /etc/fstab; автоотката нет.",
		},
	},
	EN: {
		"PRE": {
			Title:       "Preconditions & checks",
			What:        "Refreshes the apt package index, creates a sudo admin user with an SSH key, and verifies the OS version and hardening mode.",
			Why:         "Guarantees a working non-root login exists and that package installs won't fail before setup even begins.",
			RiskWithout: "The very first package install can fail, and locking down SSH with no fallback user means total loss of server access.",
			OnBox:       "Creates a user (adduser) in the sudo and sshusers groups, installs the key into /home/<user>/.ssh/authorized_keys, writes NOPASSWD rule /etc/sudoers.d/90-<user>; in soft mode sets a console password (chpasswd).",
			Revert:      "deluser --remove-home <user> + delgroup sshusers; remove /etc/sudoers.d/90-<user>; no auto-rollback in the app.",
		},
		"A1": {
			Title:       "Firewall",
			What:        "Closes all inbound ports except SSH using iptables (IPv4 and IPv6) and persists the rules across reboots. A safety timer auto-reverts the rules if the connection drops.",
			Why:         "The server stops being reachable on any service but the ones you need, and the timer prevents accidentally locking yourself out.",
			RiskWithout: "Any service that happens to listen on a port is exposed to the whole internet for attack and scanning.",
			OnBox:       "iptables/ip6tables rules (INPUT DROP policy) saved to /etc/iptables/rules.v4 and rules.v6; iptables-persistent package; a backup in /root/iptables-backup.v4/.v6 and the fail-safe script /usr/local/sbin/fw-rollback.sh.",
			Revert:      "iptables -P INPUT ACCEPT; iptables -F (and ip6tables) or iptables-restore < /root/iptables-backup.v4; then netfilter-persistent save; optionally apt purge iptables-persistent; no auto-rollback.",
		},
		"A8": {
			Title:       "Full upgrade & reboot",
			What:        "Installs all available system updates and reboots the server, confirming a clean boot by checking the boot_id changed.",
			Why:         "Closes known kernel and package vulnerabilities and gets the server onto fresh versions before fine-tuning.",
			RiskWithout: "The system stays on an outdated kernel and packages carrying publicly known security holes.",
			OnBox:       "Runs apt-get full-upgrade (upgrades packages and the kernel) and reboots; writes no persistent config files.",
			Revert:      "Package upgrades are not normally rolled back; to revert a kernel pick the previous entry in GRUB and pin it (apt-mark hold); no auto-rollback.",
		},
		"A2": {
			Title:       "SSH hardening",
			What:        "Disables password login, allows only modern strong crypto algorithms, and restricts SSH access to members of the sshusers group.",
			Why:         "Makes SSH password guessing impossible and leaves only robust key-based auth with strong ciphers.",
			RiskWithout: "SSH stays open to password brute-forcing and accepts weak, outdated encryption.",
			OnBox:       "/etc/ssh/sshd_config.d/00-hardening.conf and 99-hardening.conf; post-quantum KEX mlkem768x25519-sha256 on 26.04; ssh service restart.",
			Revert:      "delete drop-in files + systemctl restart ssh; if root password is locked, unlock via provider console (passwd -u root); no auto-rollback, but dangerous changes have a ~300s fail-safe on verify failure.",
		},
		"A2.5": {
			Title:       "Cloud-init neutralization",
			What:        "Disables the cloud-init service once the server's initial provisioning is complete.",
			Why:         "Stops the provider's cloud-init from reverting your SSH and network hardening on every reboot.",
			RiskWithout: "Any future reboot can silently roll parts of your SSH and network config back to insecure defaults.",
			OnBox:       "Creates the flag file /etc/cloud/cloud-init.disabled; does not remove the cloud-init packages themselves.",
			Revert:      "rm /etc/cloud/cloud-init.disabled — cloud-init re-enables on the next boot; no auto-rollback.",
		},
		"A3": {
			Title:       "fail2ban",
			What:        "Installs fail2ban, which watches the journal and temporarily bans IPs after repeated failed logins. Your admin IP is whitelisted.",
			Why:         "Automatically cuts off bots brute-forcing access and reduces log noise.",
			RiskWithout: "Attackers can hammer SSH with endless failed attempts with no throttling at all.",
			OnBox:       "fail2ban and python3-systemd packages; config /etc/fail2ban/jail.local (sshd jail, whitelisted IPs), plus /etc/fail2ban/jail.d/sshd-port.local on a non-standard port; fail2ban service enabled.",
			Revert:      "systemctl disable --now fail2ban; remove /etc/fail2ban/jail.local (and jail.d/sshd-port.local); optionally apt purge fail2ban; no auto-rollback.",
		},
		"A4": {
			Title:       "Network tuning",
			What:        "Enables the BBR congestion-control algorithm and enlarges socket buffers and network queues via sysctl.",
			Why:         "Improves throughput and stability of network connections, especially over long-distance links.",
			RiskWithout: "Network performance stays at conservative defaults, leaving the link's capacity unused.",
			OnBox:       "/etc/sysctl.d/99-bbr.conf (tcp_congestion_control=bbr, default_qdisc=fq) and 99-net-tune.conf (buffer sizes); tcp_bbr kernel module; persists across reboot.",
			Revert:      "delete both files + sysctl --system; the kernel module unloads on next reboot; no auto-rollback in the app.",
		},
		"A5": {
			Title:       "Kernel hardening",
			What:        "Uses sysctl to restrict kernel info leaks, protect symlinks, block route/redirect spoofing, and disable memory core dumps.",
			Why:         "Makes local privilege escalation and network spoofing harder, leaving fewer points to attack.",
			RiskWithout: "The kernel hands attackers addresses and exploit hints and accepts potentially malicious network packets.",
			OnBox:       "/etc/sysctl.d/99-zz-kernel-harden.conf (kptr_restrict, ptrace_scope, rp_filter=1, core_pattern=|/bin/false, etc.); THP=madvise via /etc/default/grub (update-grub).",
			Revert:      "delete 99-zz-kernel-harden.conf + sysctl --system; remove transparent_hugepage=madvise from /etc/default/grub + update-grub; no auto-rollback (rp_filter=1 has a ~300s fail-safe on verify failure).",
		},
		"A6": {
			Title:       "System maintenance",
			What:        "Caps systemd journal size, sets services to restart non-interactively, raises the open-file limit, and checks time sync.",
			Why:         "Keeps logs from filling the disk, ensures clean restarts after updates, and keeps accurate system time.",
			RiskWithout: "Logs can fill the disk, updates can hang on a prompt, and services can hit a too-low file limit.",
			OnBox:       "drop-ins /etc/systemd/journald.conf.d/99-vps-cap.conf, /etc/needrestart/conf.d/50-autorestart.conf, /etc/systemd/system.conf.d/limits.conf; runs timedatectl set-ntp.",
			Revert:      "delete the three drop-in files; systemctl restart systemd-journald + systemctl daemon-reexec; no auto-rollback.",
		},
		"A6.5": {
			Title:       "DNS hardening",
			What:        "Configures systemd-resolved to validate DNSSEC and encrypt lookups via DNS-over-TLS in an opportunistic mode.",
			Why:         "Makes DNS tampering and eavesdropping harder without breaking compatibility on ordinary networks.",
			RiskWithout: "DNS queries travel in cleartext with no authenticity check and are easily spoofed or sniffed.",
			OnBox:       "drop-in /etc/systemd/resolved.conf.d/99-morgward-dns.conf (DNS= set to the measured fastest resolvers, DNSOverTLS=opportunistic, DNSSEC=allow-downgrade); restarts systemd-resolved.",
			Revert:      "delete 99-morgward-dns.conf + systemctl restart systemd-resolved (provider DNS returns); no auto-rollback (the step self-reverts if resolution breaks).",
		},
		"A6.7": {
			Title:       "Memory management",
			What:        "Enables compressed in-RAM swap (ZRAM, zstd) and installs earlyoom, which gently kills processes before a hard out-of-memory.",
			Why:         "Effectively expands usable memory and prevents the server from freezing when memory runs out.",
			RiskWithout: "On a low-memory box the server can freeze entirely or hard-kill an important process under memory pressure.",
			OnBox:       "systemd-zram-generator and earlyoom packages; /etc/systemd/zram-generator.conf (zram = ram/2, zstd) and /etc/sysctl.d/99-zram.conf (swappiness=180); disables disk swap (swapoff + comments out swap in /etc/fstab).",
			Revert:      "systemctl disable --now earlyoom; delete zram-generator.conf and 99-zram.conf; restore the swap line in /etc/fstab and swapon -a; optionally apt purge systemd-zram-generator earlyoom; no auto-rollback.",
		},
		"A7": {
			Title:       "System cleanup",
			What:        "Removes packages unneeded on a server (firmware tools, crash reporters, and other bloat), logging the list first.",
			Why:         "Shrinks the attack surface and resource use by stripping out unnecessary services.",
			RiskWithout: "Extra packages keep needless services and timers running, widening the attack surface and resource use.",
			OnBox:       "apt purge of bloat (apport, whoopsie, sysstat, packagekit, fwupd on guests, multipath-tools when safe) + apt autoremove --purge; the removed list is written to /root/vps-purged-packages.log.",
			Revert:      "Package removal is irreversible; reinstall from the list in /root/vps-purged-packages.log with apt install <packages>; no auto-rollback.",
		},
		"A9": {
			Title:       "Unattended security updates",
			What:        "Enables unattended-upgrades to auto-install security updates via a separate drop-in file, with auto-reboot left off.",
			Why:         "Critical patches install themselves without manual work, while reboots stay under your control.",
			RiskWithout: "Security fixes must be applied by hand, leaving the server vulnerable for long stretches between updates.",
			OnBox:       "unattended-upgrades package; /etc/apt/apt.conf.d/20auto-upgrades (enables the periodic jobs) and 52-unattended-upgrades-local (Automatic-Reboot false, kernel cleanup).",
			Revert:      "delete both files from /etc/apt/apt.conf.d/ (or systemctl disable --now apt-daily-upgrade.timer); optionally apt purge unattended-upgrades; no auto-rollback.",
		},
		"A10": {
			Title:       "Detection & monitoring",
			What:        "Installs auditd to log changes to sensitive files, notifications for successful SSH logins, and logging of dropped packets.",
			Why:         "Builds a forensic trail and alerts you to intrusion, whereas fail2ban only sees failed attempts.",
			RiskWithout: "A successful breach, config tampering, and privilege escalation all go unnoticed and leave no trail.",
			OnBox:       "auditd/audispd-plugins packages + rules /etc/audit/rules.d/99-vps.rules; PAM notify hook /usr/local/sbin/ssh-login-notify.sh (line in /etc/pam.d/sshd); iptables LOG rules; in strict mode /etc/modprobe.d/99-vps-blacklist.conf and nodev/nosuid/noexec for /dev/shm in /etc/fstab.",
			Revert:      "systemctl disable --now auditd; remove 99-vps.rules, the line in /etc/pam.d/sshd and ssh-login-notify.sh; drop the LOG rules (iptables -D INPUT …); in strict mode remove 99-vps-blacklist.conf and the /dev/shm line in /etc/fstab; no auto-rollback.",
		},
	},
}
